include:
  - compose.infra.yaml

volumes:
  postgres-data:
  static:
  media:

networks:
  frontend:
  backend:

services:
  nginx:
    image: nginx:alpine
    restart: always
    networks:
      - frontend
    depends_on:
      - django
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./volumes/logs:/etc/nginx/logs
      - static:/usr/share/nginx/html/static
      - media:/usr/share/nginx/html/media
    ports:
      - "81:80"

  django:
    image: kolenich/family_tree
    networks:
      - frontend
      - backend
    volumes:
      - ./volumes/logs:/app/logs
      - static:/app/static
      - media:/app/media
    restart: always
    depends_on:
      - postgres
    env_file: ".env"


