include:
  - compose.infra.yaml

volumes:
  postgres-data:

services:
  nginx:
    image: nginx:alpine
    restart: always
    depends_on:
      - django-server
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./volumes/static:/usr/share/nginx/html/static
      - ./volumes/media:/usr/share/nginx/html/media
      - ./volumes/logs:/etc/nginx/logs
    ports:
      - "81:80"

  django-server:
    volumes:
      - ./volumes/static:/app/static
      - ./volumes/media:/app/media
      - ./volumes/logs:/app/logs
      - ./volumes/dumps:/app/dumps
    build:
      context: .
    restart: always
    depends_on:
      - postgres
    env_file: ".env"


