version: "3.8"

networks:
  default:
    name: family-tree

volumes:
  static:
    name: static
  nginx-conf:
    name: nginx-conf

services:
  nginx:
    container_name: nginx
    image: library/nginx:alpine
    restart: always
    depends_on:
      - django-server
    volumes:
      - nginx-conf:/etc/nginx/conf.d
      - static:/usr/share/nginx/html/static
      - ./media:/usr/share/nginx/html/media
      - ./logs:/usr/share/nginx/logs
    ports:
      - "80:80"

  django-server:
    container_name: django-server
    volumes:
      - static:/app/static
      - nginx-conf:/app/nginx
      - ./media:/app/media
      - ./logs:/app/logs
    build:
      context: .
    image: django-server
    restart: always
    depends_on:
      - postgres
    environment:
      - DEBUG=false
      - DB_NAME=db
      - DB_USER=user
      - DB_PASSWORD=pass
      - DB_HOST=postgres
      - ALLOWED_HOSTS=localhost
      - SECRET_KEY=test_secret

  postgres:
    container_name: postgres
    image: library/postgres:alpine
    restart: always
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
