# Generated by Django 3.2.6 on 2021-08-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Дата смерти')),
                ('sex',
                 models.CharField(choices=[('male', 'Муж.'), ('female', 'Жен.')], max_length=6, verbose_name='Пол')),
                ('parents', models.ManyToManyField(blank=True, default=list, related_name='_members_person_parents_+',
                                                   to='members.Person', verbose_name='Родители')),
                ('siblings', models.ManyToManyField(blank=True, default=list, related_name='_members_person_siblings_+',
                                                    to='members.Person', verbose_name='Братья/Сестры')),
            ],
            options={
                'verbose_name': 'Член дерева',
                'verbose_name_plural': 'Члены дерева',
                'db_table': 'persons',
            },
        ),
    ]
