# Generated by Django 3.2.6 on 2021-08-20 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='consort',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                       to='members.person', verbose_name='Супруг/супруга'),
        ),
    ]
