# Generated by Django 3.2.6 on 2021-08-20 13:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('members', '0002_person_consort'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='siblings',
        ),
    ]
