# Generated by Django 3.2.6 on 2021-08-20 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('members', '0003_remove_person_siblings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='parents',
        ),
        migrations.AddField(
            model_name='person',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='father_of', to='members.person', verbose_name='Отец'),
        ),
        migrations.AddField(
            model_name='person',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='mother_of', to='members.person', verbose_name='Мать'),
        ),
    ]
