# Generated by Django 3.2.6 on 2021-08-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('members', '0004_auto_20210820_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Аватар'),
        ),
    ]
