# Generated by Django 3.2.6 on 2021-08-20 20:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('members', '0005_person_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='consort',
            new_name='spouse',
        ),
    ]
